### PR TITLE
Fix "Sample" is reserved INF error

### PR DESCRIPTION
**Pull request by forderud**
Proposed fix to #13 that assumes that the driver doesn't adhere to any well-known class. Use "hostude" as class name with a new unique generated class GUID.

WARNING: I haven't performed any run-time testing of the generated driver, so **please test the driver before merging**.

INF validation documentation: https://learn.microsoft.com/en-us/windows-hardware/drivers/devtest/inf-validation-errors-and-warnings

### CODE REVIEW

**Comment by xxandy** [comment]
Thanks again!  Indeed, I'll be sure to take this change for a spin before I merge.

**Comment by forderud** [comment]
Good. I just rebased the PR on top of "master" to make it easier for you to test.

**Comment by forderud** [comment]
Gentle reminder. Any progress on testing out this PR?

**Comment by forderud** [comment]
Gentle reminder.

**Comment by forderud** [comment]
I've now tested the INF-file changes myself and hereby confirm that the driver afterwards loads successfully and the associated `hostudetest.exe` test tool work as expected.

**Comment by xxandy** [comment]
sorry I haven't been able to get to testing this - and thanks so much for doing the test on your own !  I'll just accept this one now!

**Pull request merged**
